before_script:
    # Install dependencies
    - bash build/docker_install.sh > /dev/null

services:
    - mysql:latest
    - postgres:latest

variables:
    MYSQL_ROOT_PASSWORD: foo-bar-baz
    MYSQL_DATABASE: test
    MYSQL_USER: test
    MYSQL_PASSWORD: test
    POSTGRES_DB: test
    POSTGRES_USER: test
    POSTGRES_PASSWORD: test

test:7:
    image: php:7
    script:
      - phpunit -c build --no-coverage
      
test:7.1:
    image: php:7.1
    script:
      - phpunit -c build  --no-coverage