before_script:
    # Install dependencies
    - bash build/docker_install.sh > /dev/null
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install --ignore-platform-reqs
services:
    - mysql:latest
    - postgres:alpine

variables:
    MYSQL_ROOT_PASSWORD: foo-bar-baz
    MYSQL_DATABASE: test
    MYSQL_USER: test
    MYSQL_PASSWORD: test
    POSTGRES_DB: test
    POSTGRES_USER: test
    POSTGRES_PASSWORD: test

test:7.1:
    image: php:7.1-alpine
    script:
      - vendor/bin/phpunit -c build  --no-coverage

test:7.2:
    image: php:7.2-alpine
    script:
      - vendor/bin/phpunit -c build  --no-coverage
