imports:
    - php

tools:
    external_code_coverage:
        timeout: 1000
    # PHP
    
    # Don't like PSR standards, not going to get messages for them!
    php_code_sniffer: false
    
    php_sim: true
    # Can't be used with similarity analyzer
    php_cpd: false  
   
    php_mess_detector: true
    php_pdepend: true
    php_loc: true
    php_analyzer:
        config:
            doc_comment_fixes:
                enabled: true
	
    #HHVM static analysis
    php_hhvm: true