imports:
    - php

tools:
    external_code_coverage:
        timeout: 1000
    # PHP
    php_code_sniffer: true
    php_cpd: true
    php_mess_detector: true
    php_pdepend: true
    php_loc: true
    php_analyzer:
        config:
            doc_comment_fixes:
                enabled: true