language: php

before_setup:
  - sudo add-apt-repository ppa:mapopa -qq
  - sudo apt-get update -qq
  - sudo apt-get install firebird2.5-classic -qq
  - sudo dpkg-reconfigure firebird2.5-classic -qq
  - sudo apt-get install php5-interbase -qq

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5

before_script:
  - sh -c "psql -c 'DROP DATABASE IF EXISTS test;' -U postgres"
  - sh -c "psql -c 'create database test;' -U postgres"
  - sh -c "mysql -e 'create database IF NOT EXISTS test;'"

script: php ./tests/index.php
