sudo: false

language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

install:
  dpkg-reconfigure firebird2.5-superclassic

before_script:
  - psql -c 'DROP DATABASE IF EXISTS test;' -U postgres
  - psql -c 'create database test;' -U postgres
  - mysql -e 'create database IF NOT EXISTS test;'

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

addons:
  apt:
    packages:
      - php5-interbase
      - firebird2.5-superclassic

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml