language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5

before_script:
  - sh -c "psql -c 'DROP DATABASE IF EXISTS test;' -U postgres"
  - sh -c "psql -c 'create database test;' -U postgres"
  - sh -c "mysql -e 'create database IF NOT EXISTS test;'"
  - phpenv config-add ./tests/php_test.ini

script: php ./tests/index.php
